In [1]:
from IPython.display import display
import pandas as pd

In [7]:
pd.set_option('display.max_colwidth', None)

In [2]:
path = "../data/interim/ambiguous/20240202.1101_Q79_Q34_Q16_PN_ambiguous.csv"
prev_gf_wordnet = pd.read_csv(path, index_col=0, delimiter="\t").reset_index(drop=True).drop("no_en_entry", axis=1)

In [8]:
display(prev_gf_wordnet)

,en_entry,ar,pos,MorphoDictAra
0,magdalena_4_GN,ماجْدالينا,GN,"lin magdalena_4_GN = mkLT ""ماجْدالينا_GN"" ;"
1,mustafa_8_GN,مصطفى,GN,"lin mustafa_8_GN = mkLT ""مصطفى_GN"" ;"
2,ulf_3_GN,أولْف,GN,"lin ulf_3_GN = mkLT ""أولْف_GN"" ;"
3,alexandria_governorate_7_LN,محافظة الاسكندرية,LN,"lin alexandria_governorate_7_LN = mkLT ""محافظة_الاسكندرية_LN"" ;"
4,aswan_governorate_1_LN,محافظة أسوان,LN,"lin aswan_governorate_1_LN = mkLT ""محافظة_أسوان_LN"" ;"
...,...,...,...,...
103,unesco_PN,اليونسكو,PN,"lin unesco_PN = mkLT ""اليونسكو_PN"" ;"
104,united_states_LN,الولايات المتحدة,LN,"lin united_states_LN = mkLT ""الولايات_المتحدة_LN"" ;"
105,windsor_2_SN,وندسور,SN,"lin windsor_2_SN = mkLT ""وندسور_SN"" ;"
106,yukon_2_LN,يوكون,LN,"lin yukon_2_LN = mkLT ""يوكون_LN"" ;"
107,abd_al-fattāḥ_2_GN,عبد الفتاح GN,0,"lin abd_al-fattāḥ_2_GN = mkLT ""عبد_الفتاح_GN_0"" ;"

In [9]:
prev_gf_wordnet["MorphoDictAra"] = prev_gf_wordnet.apply(
    lambda x: f'lin {x.en_entry} = mkLT "{"_".join(x.ar.split())}_{x.pos}" ;', axis=1
)

In [10]:
display(prev_gf_wordnet)

,en_entry,ar,pos,MorphoDictAra
0,magdalena_4_GN,ماجْدالينا,GN,"lin magdalena_4_GN = mkLT ""ماجْدالينا_GN"" ;"
1,mustafa_8_GN,مصطفى,GN,"lin mustafa_8_GN = mkLT ""مصطفى_GN"" ;"
2,ulf_3_GN,أولْف,GN,"lin ulf_3_GN = mkLT ""أولْف_GN"" ;"
3,alexandria_governorate_7_LN,محافظة الاسكندرية,LN,"lin alexandria_governorate_7_LN = mkLT ""محافظة_الاسكندرية_LN"" ;"
4,aswan_governorate_1_LN,محافظة أسوان,LN,"lin aswan_governorate_1_LN = mkLT ""محافظة_أسوان_LN"" ;"
...,...,...,...,...
103,unesco_PN,اليونسكو,PN,"lin unesco_PN = mkLT ""اليونسكو_PN"" ;"
104,united_states_LN,الولايات المتحدة,LN,"lin united_states_LN = mkLT ""الولايات_المتحدة_LN"" ;"
105,windsor_2_SN,وندسور,SN,"lin windsor_2_SN = mkLT ""وندسور_SN"" ;"
106,yukon_2_LN,يوكون,LN,"lin yukon_2_LN = mkLT ""يوكون_LN"" ;"
107,abd_al-fattāḥ_2_GN,عبد الفتاح GN,0,"lin abd_al-fattāḥ_2_GN = mkLT ""عبد_الفتاح_GN_0"" ;"

In [1]:
# with open("/mnt/c/Users/moham/Downloads/csv/nouns.dict.csv") as fobj:
#     print(fobj.read())
import pandas as pd
pd.set_option('display.max_colwidth', None)
pd.set_option('display.max_columns', None)
diction = pd.read_csv("/mnt/c/Users/moham/Downloads/csv/nouns.dict.csv", skiprows=10, delimiter="\t", index_col=0)
diction.dropna(subset=["unvocalized"], inplace=True)

In [2]:
diction["number"].value_counts()

number
مفرد         21944
جمع تكسير     8226
number           8
Name: count, dtype: int64

In [5]:
diction[diction["unvocalized"].str.contains("جمال")]
# diction[diction["unvocalized"] == "إجمالي"]

,vocalized,unvocalized,normalized,stamped,wordtype,root,wazn,category,original,gender,feminin,masculin,number,single,broken_plural,defined,mankous,feminable,dualable,masculin_plural,feminin_plural,mamnou3_sarf,relative,w_suffix,hm_suffix,kal_prefix,ha_suffix,k_prefix,annex,definition,note
#id,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
1757,جِمَالٌ,جمال,جمال,جمل,جامد,جمل,NaN,NaN,NaN,NaN,NaN,NaN,جمع تكسير,جَمَلٌ,NaN,0,0,0,0,0,0,0,0,0,1,1,1,1,0,NaN,:لا شرح
173,إِجْمَالٌ,إجمال,ءجمال,إجمل,مصدر,جمل,NaN,مصدر,أَجْمَلَ,مذكر,NaN,NaN,مفرد,NaN,NaN,0,0,0,1,0,1,0,1,0,1,1,1,1,0,"إِجْمَالٌ-إِجْمَالٌ [ج م ل] (مص. أَجْمَلَ). 1.""بالإجْمَالِ كَانَتِ النَّتَائِجُ حَسَنَةً"" : بِوَجْهٍ عَامٍّ، بشَكْلٍ عَامٍّ. ""عَلَى الإِجْمَالِ"" ""بِوَجْهِ الإِجْمَالِ كَانَتِ الحَفْلَةُ مُوَفَّقَةً"". 2.""إِجْمَالاً لَمْ يَتَخَلَّفْ عَنِ الحُضُورِ إِلاَّ القَلِيلُ"" : عُمُومًا.",NaN
3141,جَمَالٌ,جمال,جمال,جمل,مصدر,جمل,NaN,مصدر,جَمُلَ;جَمِلَ,مذكر,NaN,NaN,مفرد,NaN,NaN,0,0,0,1,0,1,0,1,0,1,1,1,1,0,"جَمَالٌ-جَمَالٌ [ج م ل] (مص. جَمُلَ، جَمِلَ). ""جَمَالُهَا فَاتِنٌ"": حُسْنُهَا، بَهَاؤُهَا. 2.""جَمَال"" : اِسْمُ عَلَمٍ للذُّكُورِ.",NaN
349,جَمَّالٌ,جمال,جمال,جمل,صيغة مبالغة,جمل,فَعَّال,صيغة,NaN,مذكر,NaN,NaN,مفرد,NaN,NaN,0,0,1,1,1,1,1,0,1,1,1,1,1,0,". ""وَقَفَ الجَمَّالُ يُرَاقِبُ جِمَالَهُ"" : صَاحِبُ الجِمَالِ.",NaN

In [13]:
import pandas as pd
d = {
    "LN": {"abergele_LN": "أبيرجيلي", "abertillery_LN": "أبرتيليري"},
    "PN": {"ada_PN": "آدا", "ana_1_PN": "آنا"},
    "SN": {"alger_SN": "الجزائر", "ali_SN": "علي"},
}
p = pd.DataFrame(d["LN"].items(), columns=["wordnet_entry", "translation"])

In [16]:
p

    wordnet_entry translation
0     abergele_LN    أبيرجيلي
1  abertillery_LN   أبرتيليري

In [14]:
d = {}
p1 = pd.DataFrame(d.items(), columns=["wordnet_entry", "translation"])

In [15]:
p1

Empty DataFrame
Columns: [wordnet_entry, translation]
Index: []

In [17]:
pd.concat((p,p1))

    wordnet_entry translation
0     abergele_LN    أبيرجيلي
1  abertillery_LN   أبرتيليري